### ISSUE TITLE
Boto3 version on lambda doesn't support the API

### ISSUE THREAD

**Issue by alessandrobologna** [awslabs/ecs-cid-sample#3]
Thank you for this example, but it would be useful to add in the readme that the current version of Boto3 installed on the lambda AMI doesn't include the update_container_instances_state() method for the ecs client.
I know that adding the zip file with all boto3 included solves the problem, but when I tried to just deploy the python code without realizing that there was a reason for putting the entire zip there, I was a bit confused. 
Hopefully the lambda AMI will be updated soon, and this can be closed.

**Comment by alessandrobologna** [comment]
I realize this was already pointed out: https://github.com/awslabs/ecs-cid-sample/issues/2 but the issue is closed, so it's not obvious to the reader that there's the need to include the proper version of the library

**Comment by mperi** [comment]
Updated README.MD with a note calling out attention to the same. Thanks.

**Comment by jharley** [comment]
Lambda has since updated its version of boto3 to one including `update_container_instances_state`
