### ISSUE TITLE
AutoScalingReplacingUpdate with WillReplace set to "true"

### ISSUE THREAD

**Issue by alessandrobologna** [awslabs/ecs-cid-sample#4]
Hi, just a question to see if somebody already has a solution: if my ASG is using an [AutoScalingReplacingUpdate policy with WillReplace set to True](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html) what would be the approach to drain tasks and move them to the new ASG before the replacement takes place?

**Comment by mperi** [comment]
Regardless of the scaling policy, DRAINING state for containers setting should be invoked before terminating an instance via the lifecycle hook as explained in the blog https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/  . Amazon ECS prevents new tasks from being scheduled for placement on the container instance and replacement service tasks are started on other container instances in the cluster if the resources are available. Service tasks on the container instance that are in the PENDING state are stopped immediately.

The instance termination can then proceed safely. 

The AutoScalingReplacingUpdate will be terminating instances ONLY after new instances are available and stable. So, your ECS cluster already would have resources to place the tasks.
